### PR TITLE
Use hackney as the default adapter for GoogleApiClient

### LINKED ISSUE #18: Without return_immediately: true, acknowledge messages get "stuck"
### The Problem

Using the default `GoogleApiClient` without `return_immediately: true`, there is a high likelihood that messages will not be acknowledged before they reach their deadline.

**Background Info**

If there are no messages in the topic queue, the subscription "pull request" will be held open for a "bounded amount of time", _unless_ the user specifies [return_immediately: true](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/pull), at which point the server will respond immediately with an empty list† and the producer will have to wait the entire `:receive_interval` before beginning another pull request.

Currently, an acknowledge request can get blocked by an in-flight pull request, at which point the messages being acknowledged are almost certainly going to be returned to the queue, as they will have exceeded their deadline by the time the acknowledge request is actually sent.

As laid out in googleapis/elixir-google-api#98, all GoogleApi connections currently default to using Tesla with the httpc adapter. As of the latest version of Gax (0.1.3), this behavior is still not directly configurable.

### Possible Solutions

**1) Recommend global adapter configuration**

We could recommend that users install and configure a global adapter for Tesla. This would resolve the issues with httpc, but it still won't allow for per-request adapter configuration, which we really need so we can hold open the pull request until a message arrives or the server disconnects us.

**2) Wait for vendor adoption**

We could wait for Gax to support Tesla 1.2, at which point we should be able to provide runtime adapter configuration. If/when that happens, the next question would be how much of this adapter-related configuration should be exposed to end users?

**3) Ship with a working adapter**

Ideally, as an end user, I can ignore all of the adapter complexity and just focus on handling messages. One way for that to be true would be to add the following dependencies:

```elixir
# BroadwayCloudPubSub.MixProject
def deps() do
  [
    {:tesla, "~> 1.2.0"},
    {:hackney, "~> 1.6"}
  ]
end
```

and then inject the adapter into the Tesla.Client _after_ it's been created: 

```elixir
defmodule BroadwayCloudPubSub.GoogleApiClient.Connection do
  alias GoogleApi.PubSub.V1.Connection, as: V1Connection

  def new(token, adapter_opts \\ []) do
    token
    |> V1Connection.new()
    |> override_adapter(adapter_opts)
  end

  defp override_adapter(client, opts \\ []) do
    %{adapter: adapter} = Tesla.client([], {Tesla.Adapter.Hackney, opts})
    %{client | adapter: adapter}
  end
end
```

so that we can set adapter options at runtime:

```elixir
defmodule BroadwayCloudPubSub.GoogleApiClient do
  def receive_messages(demand, opts) do
    opts
    |> token!()
    |> GoogleApiClient.Connection.new(recv_timeout: :infinity)
    |> pubsub_projects_subscriptions_pull()
  end

  def ack({_, ref} = ack_ref, successful, _failed) do
    opts = Broadway.TermStorage.get!(ref)

    opts
    |> token!()
    |> GoogleApiClient.Connection.new()
    |> pubsub_projects_subscriptions_acknowledge()
  end
end
```

**Steps to Reproduce:**
* Follow the Google Cloud Pub/Sub How-to guide for [Testing apps locally with the emulator](https://cloud.google.com/pubsub/docs/emulator) to run the Pub/Sub emulator and create a topic and subscription.
* Configure a Broadway pipeline using `BroadwayCloudPubSub.Producer`.
* _Be sure to give your pipeline some work to do._ This bug doesn't exhibit as easily if the Processors immediately return a successfully processed message.
* Override the `:base_url` for Pub/Sub in the app configuration:
    ```elixir
    config :google_api_pub_sub, base_url: "http://localhost:8085"
    ```
* Start the pipeline, and ensure it is connecting to the Pub/Sub emulator instance running locally.
* Publish messages to the topic. Using the sample lib from the How-to guide, you can run the following command:
    ```sh
    python publisher.py <PROJECT_ID> publish <TOPIC_NAME>
    ```
* You should see the same messages being processed multiple times, possibly to the point where the queue is never drained.

† When the queue is empty, the PullResponse struct actually returns nil for receivedMessages, which [breaks the typespec](https://hexdocs.pm/google_api_pub_sub/0.9.0/GoogleApi.PubSub.V1.Model.PullResponse.html#t:t/0), but I digress.

Thoughts? @wojtekmach @msaraiva @josevalim

### PR DESCRIPTION
**Pull request by mcrumm**
This PR handles the adapter overrides for the `Tesla.Client` structs built by the `:google_api_pub_sub` library.  This change makes hackney the HTTP adapter for BroadwayCloudPubSub connections.  To accommodate this, hackney is now a required dependency for `:broadway_cloud_pub_sub`, along with Tesla 1.2.

To ensure we could still replace the Tesla adapter with the mock adapter in our tests, I exposed a `:connection` option for `GoogleApiClient`, but I purposefully did not document it, as it's really not intended to be overridden by a user-level implementation. Better to document it as an internal option, or leave it as-is?

Closes #18

### CODE REVIEW

**Comment by mcrumm** [comment]
I created a separate issue to discuss the connection pool (#19) because I don't think the producer currently has enough information to make any determination as to the proper pool size.

File: lib/broadway_cloud_pub_sub/google_api_client/connection.ex [hunk 1]
```diff
@@ -0,0 +1,19 @@
+defmodule BroadwayCloudPubSub.GoogleApiClient.Connection do
```
Comment (josevalim) [inline lib/broadway_cloud_pub_sub/google_api_client/connection.ex]: Apologies for the tiny bike shedding but do we need a separate module at all? The implementation for both modules is the same and we don't want to expose this to the user anyway, so I would keep it in the main client module and simply have an option that sets the internal tesla adapter to Tesla.Mock (which is ugly but again, since we don't expose and it is an internal implementation detail, it is totally fine). I would even call the option "__internal_tesla_adapter__". Thoughts?

Comment (mcrumm) [reply lib/broadway_cloud_pub_sub/google_api_client/connection.ex]: Thanks for the input! That sounds much better.

**Comment by mcrumm** [comment]
@josevalim Thank you for the suggestions -- reduced complexity FTW!

File: mix.exs [hunk 2]
```diff
@@ -34,6 +34,8 @@ defmodule BroadwayCloudPubSub.MixProject do
     [
       {:broadway, "~> 0.3.0"},
       {:google_api_pub_sub, "~> 0.4"},
+      {:tesla, "~> 1.2.0"},
+      {:hackney, "~> 1.6"},
```
Comment (wojtekmach) [inline mix.exs]: I'm ok with making hackney required to keep it simple,  we now can additionally simplify installation guide: https://github.com/plataformatec/broadway_cloud_pub_sub/blob/master/README.md#installation

If someone would rather use a different adapter I think we can revisit this in the future and drop the dependency on hackney but still make it de-facto required as in people would have to add it to their deps list.
